import { useState, useEffect, useCallback, useMemo, useRef, Fragment } from "react";
import { useNavigate } from "react-router-dom";
import { Loader2, RefreshCw, Copy, Sparkles, Plus, Layers, CloudOff, AlertCircle, Link2, Search, Package, ChevronRight } from "lucide-react";
import api from "../api";
import toast from "react-hot-toast";
import { useAuth } from "../AuthContext";
import { TopBar, BtnPrimary, BtnSecondary, BtnDanger, Modal, parseDisplayName } from "../components/UI";
import { SearchableSelect } from "../components/ProductPickerDrawer";
import ProductionGuideButton from "../components/ProductionGuide";

/* Phase 13.0.2 — Batch ID generator + registry.
   Batch IDs are generated by the portal (V6 standard), never typed. */

export const SYNC_BADGE = {
  staged: { label: "Staged",  cls: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300" },
  done:   { label: "In Odoo", cls: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300" },
  error:  { label: "Sync error", cls: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300" },
};

export function SyncBadge({ status }) {
  const b = SYNC_BADGE[status] || SYNC_BADGE.staged;
  return <span className={`inline-flex text-xs font-medium px-2 py-0.5 rounded-full ${b.cls}`}>{b.label}</span>;
}

// Compact per-stage indicator used inside an expanded registry group, where a
// full pill per stage chip would be too busy.
const SYNC_DOT_COLOR = { staged: "bg-amber-400", done: "bg-green-500", error: "bg-red-500" };
function SyncDot({ status }) {
  const b = SYNC_BADGE[status] || SYNC_BADGE.staged;
  return <span className={`inline-block w-1.5 h-1.5 rounded-full ${SYNC_DOT_COLOR[status] || SYNC_DOT_COLOR.staged}`} title={b.label} />;
}

export const fmtWhen = (v) =>
  v ? new Date(v).toLocaleString("en-ZA", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Africa/Johannesburg" }) : "";

// Plain-language stage names, keyed by the batch ID's trailing suffix.
// Mirrors STAGE_SUFFIXES in backend services/batch_id.py.
export const STAGE_LABELS = {
  D: "Drying", U: "Unmanicured", M: "Manicured", P: "Pops", T: "Trim",
  PC: "Crushed (standard)", TC: "Crushed (budget)",
  PCPR: "Pre Roll (standard)", TCPR: "Pre Roll (budget)",
  PCPRPTT: "Pop Top Tube (standard)", TCPRPTT: "Pop Top Tube (budget)",
  PCPRPJR: "Jar (standard)", TCPRPJR: "Jar (budget)",
  MP1G: "Mylar 1g (Manicured)", MP3G: "Mylar 3g (Manicured)", MP5G: "Mylar 5g (Manicured)",
  PP1G: "Mylar 1g (Pops)", PP3G: "Mylar 3g (Pops)", PP5G: "Mylar 5g (Pops)",
};

export const stageLabel = (batchId) => {
  const tail = (batchId || "").split("-").pop();
  return STAGE_LABELS[tail] || null;
};

// Hover text for any batch ID: "Dantes Inferno — Unmanicured"
export const batchTitle = (batchId, productName) =>
  [productName, stageLabel(batchId)].filter(Boolean).join(" — ");

export default function BatchRegistry() {
  const { can } = useAuth();
  const navigate = useNavigate();
  const [meta, setMeta]         = useState(null);
  const [products, setProducts]   = useState([]);
  const [items, setItems]       = useState([]);
  const [loading, setLoading]   = useState(true);
  const [q, setQ]               = useState("");

  // Generator state — Bassani-produced batches only. Imported (BI) batches
  // are never generated here: they are created atomically by the S6
  // Receiving flow (vault receive + s6_receipts entry + quarantine), which
  // this screen has no way to replicate safely, so the endpoint refuses the
  // "import" family outright rather than relying on this UI not offering it.
  const [family, setFamily]         = useState("single");
  const [productQuery, setProductQuery] = useState("");
  const [product, setProduct]         = useState(null);   // {name, code}
  const [productOpen, setProductOpen] = useState(false);
  const [preview, setPreview]       = useState(null);   // {batch_id, sequence}
  const [generating, setGenerating] = useState(false);
  const productBoxRef = useRef(null);

  // Manage-products modal (production.manage)
  const [manageOpen, setManageOpen]       = useState(false);
  const [manageList, setManageList]       = useState([]);
  const [manageSearch, setManageSearch]   = useState("");
  const [newProduct, setNewProduct]         = useState({ name: "", code: "" });
  const [savingProduct, setSavingProduct]   = useState(false);
  const [productBusy, setProductBusy]       = useState(null);   // code currently being archived/restored/deleted
  const [deleteProductConfirm, setDeleteProductConfirm] = useState(null);  // product row
  // Link-to-Odoo-product picker (production.manage) — same category/variant/
  // search browsing as the commercial quote builder's Browse Products drawer,
  // since products and categories are global in Odoo (only stock quantity is
  // warehouse-scoped, and irrelevant to picking which record to link).
  const [linkTarget, setLinkTarget]             = useState(null);   // product row
  const [linkCategories, setLinkCategories]     = useState([]);
  const [linkCatLoaded, setLinkCatLoaded]       = useState(false);
  const [linkSelectedCat, setLinkSelectedCat]   = useState(null);
  const [linkSelectedVariant, setLinkSelectedVariant] = useState(null);
  const [odooProductQuery, setOdooProductQuery] = useState("");
  const [odooProductResults, setOdooProductResults] = useState([]);
  const [odooProductSearching, setOdooProductSearching] = useState(false);

  // Registry grouping — one expandable row per physical batch lineage rather
  // than one row per stage, so the table stays readable once a batch has
  // moved through several stages. expandedGroups tracks which base batches
  // are open; groupDetail caches each group's fetched stage/movement history.
  const [expandedGroups, setExpandedGroups] = useState({});
  const [groupDetail, setGroupDetail]       = useState({});

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [metaRes, productRes, listRes] = await Promise.all([
        api.get("/api/production/meta"),
        api.get("/api/production/products"),
        api.get("/api/production/batches", { params: q ? { q, limit: 200 } : { limit: 200 } }),
      ]);
      setMeta(metaRes.data);
      setProducts(productRes.data.products);
      setItems(listRes.data.items);
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to load batch registry");
    } finally {
      setLoading(false);
    }
  }, [q]);

  useEffect(() => { load(); }, [load]);

  // Live ID preview as the operator picks the family + product
  useEffect(() => {
    if (!product) { setPreview(null); return; }
    let stale = false;
    api.get("/api/production/batches/preview", { params: { family, product_code: product.code } })
      .then(r => { if (!stale) setPreview(r.data); })
      .catch(() => { if (!stale) setPreview(null); });
    return () => { stale = true; };
  }, [family, product]);

  // Close product dropdown on outside click
  useEffect(() => {
    const close = (e) => {
      if (productBoxRef.current && !productBoxRef.current.contains(e.target)) setProductOpen(false);
    };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, []);

  const filteredProducts = products.filter(s => {
    const t = productQuery.trim().toLowerCase();
    if (!t) return true;
    return s.name.toLowerCase().includes(t) || s.code.toLowerCase().includes(t);
  });

  async function generate() {
    if (!product || !preview) return;
    setGenerating(true);
    try {
      const r = await api.post("/api/production/batches", { family, product_code: product.code });
      toast.success(`Batch ${r.data.batch.batch_id} created`);
      setItems(prev => [r.data.batch, ...prev]);
      setPreview(null);
      // refresh the preview for the next sequence number
      const p = await api.get("/api/production/batches/preview", { params: { family, product_code: product.code } });
      setPreview(p.data);
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to create batch");
    } finally {
      setGenerating(false);
    }
  }

  // Refresh both the manage list (incl. archived) and the generator picker (active only)
  async function refreshProducts() {
    const [all, active] = await Promise.all([
      api.get("/api/production/products", { params: { include_archived: true } }),
      api.get("/api/production/products"),
    ]);
    setManageList(all.data.products);
    setProducts(active.data.products);
  }

  async function openManage() {
    setManageOpen(true);
    try { await refreshProducts(); } catch { toast.error("Failed to load product list"); }
  }

  async function saveProduct() {
    setSavingProduct(true);
    try {
      await api.post("/api/production/products", { name: newProduct.name, code: newProduct.code });
      toast.success(`Product ${newProduct.name} added`);
      setNewProduct({ name: "", code: "" });
      await refreshProducts();
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to add product");
    } finally {
      setSavingProduct(false);
    }
  }

  async function toggleProduct(s) {
    setProductBusy(s.code);
    try {
      await api.post(`/api/production/products/${s.code}/${s.active ? "archive" : "restore"}`);
      toast.success(s.active ? `${s.name} archived and hidden from the picker` : `${s.name} restored`);
      await refreshProducts();
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to update product");
    } finally {
      setProductBusy(null);
    }
  }

  async function doDeleteProduct() {
    const s = deleteProductConfirm;
    setDeleteProductConfirm(null);
    setProductBusy(s.code);
    try {
      await api.delete(`/api/production/products/${s.code}`);
      toast.success(`${s.name} removed from the master list`);
      await refreshProducts();
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to delete product");
    } finally {
      setProductBusy(null);
    }
  }

  async function doLinkProduct(odooProduct) {
    const s = linkTarget;
    setLinkTarget(null);
    setProductBusy(s.code);
    try {
      await api.post(`/api/production/products/${s.code}/link`, {
        odoo_product_id: odooProduct.id,
        odoo_product_name: odooProduct.display_name || odooProduct.name,
      });
      toast.success(`${s.name} linked to ${odooProduct.display_name || odooProduct.name}`);
      await refreshProducts();
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to link product");
    } finally {
      setProductBusy(null);
    }
  }

  async function doUnlinkProduct(s) {
    setProductBusy(s.code);
    try {
      await api.post(`/api/production/products/${s.code}/unlink`);
      toast.success(`${s.name} unlinked`);
      await refreshProducts();
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to unlink product");
    } finally {
      setProductBusy(null);
    }
  }

  function openLinkPicker(s) {
    setLinkTarget(s);
    setOdooProductQuery(s.name);
    setLinkSelectedCat(null);
    setLinkSelectedVariant(null);
  }

  // Load Odoo categories once, the first time the link picker is opened
  useEffect(() => {
    if (!linkTarget || linkCatLoaded) return;
    api.get("/api/production/odoo-categories")
      .then(r => setLinkCategories(r.data.categories || []))
      .catch(() => {})
      .finally(() => setLinkCatLoaded(true));
  }, [linkTarget, linkCatLoaded]);

  // Odoo product search inside the link picker: debounced on text, immediate
  // on category change — same rhythm as the quote builder's Browse Products.
  useEffect(() => {
    if (!linkTarget) { setOdooProductResults([]); return; }
    const q = odooProductQuery.trim();
    if (!q && !linkSelectedCat) { setOdooProductResults([]); return; }
    setOdooProductSearching(true);
    const t = setTimeout(() => {
      const params = { limit: 150 };
      if (q) params.q = q;
      if (linkSelectedCat) params.category_id = linkSelectedCat;
      api.get("/api/production/odoo-products", { params })
        .then(r => setOdooProductResults(r.data.products || []))
        .catch(e => toast.error(e.response?.data?.detail || "Product search failed"))
        .finally(() => setOdooProductSearching(false));
    }, q ? 300 : 0);
    return () => clearTimeout(t);
  }, [odooProductQuery, linkSelectedCat, linkTarget]);

  const linkCategoryOptions = linkCategories.map(c => ({ value: c.id, label: c.name }));

  // Variant chips derived from the currently loaded result set, same
  // "Name (Variant)" parsing the quote builder's picker uses.
  const linkVariantOptions = (() => {
    const seen = new Set();
    odooProductResults.forEach(p => {
      parseDisplayName(p.display_name || p.name || "").groups.forEach(g => seen.add(g));
    });
    return [...seen].sort().map(v => ({ value: v, label: v }));
  })();

  const linkDisplayedProducts = linkSelectedVariant
    ? odooProductResults.filter(p => parseDisplayName(p.display_name || p.name || "").groups.includes(linkSelectedVariant))
    : odooProductResults;

  // Group every registry row (base + derived stages) by physical batch
  // lineage (base_batch_id), so the table shows one row per real-world
  // batch. "Leaves" are stages nothing else in the group was derived from —
  // the batch's current physical form(s): usually one, but two after a
  // manicuring split (Manicured + Trim are separate physical items from the
  // same origin, not one replacing the other). Note: if a narrow search
  // matches only one stage of a batch, the collapsed preview is computed
  // from just that partial set — expanding always re-fetches the complete,
  // accurate history regardless, since that call is keyed by base_batch_id.
  const groups = useMemo(() => {
    const byBase = new Map();
    for (const b of items) {
      const baseId = b.base_batch_id || b.batch_id;
      if (!byBase.has(baseId)) byBase.set(baseId, []);
      byBase.get(baseId).push(b);
    }
    const syncPriority = { error: 0, staged: 1, done: 2 };
    return [...byBase.entries()].map(([baseId, entries]) => {
      entries.sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
      const base = entries.find(e => e.batch_id === baseId) || entries[0];
      const leaves = entries.filter(e => !entries.some(o => o.parent_batch_id === e.batch_id));
      const worstSync = entries.reduce(
        (w, e) => (syncPriority[e.odoo_sync] ?? 1) < (syncPriority[w] ?? 1) ? e.odoo_sync : w,
        entries[0].odoo_sync
      );
      return {
        baseId,
        product_name: base.product_name,
        leaves,
        stageCount: entries.length,
        started_at: base.created_at,
        started_by: base.created_by_name,
        syncStatus: worstSync,
        mixedSync: new Set(entries.map(e => e.odoo_sync)).size > 1,
      };
    }).sort((a, b) => new Date(b.started_at) - new Date(a.started_at));
  }, [items]);

  async function toggleGroup(baseId) {
    const willExpand = !expandedGroups[baseId];
    setExpandedGroups(prev => ({ ...prev, [baseId]: willExpand }));
    if (!willExpand) return;
    setGroupDetail(prev => ({ ...prev, [baseId]: { loading: true } }));
    try {
      const r = await api.get(`/api/production/batches/${encodeURIComponent(baseId)}/timeline`);
      setGroupDetail(prev => ({ ...prev, [baseId]: { loading: false, stages: r.data.stages, movements: r.data.movements } }));
    } catch (e) {
      setGroupDetail(prev => ({ ...prev, [baseId]: { loading: false, error: e.response?.data?.detail || "Failed to load batch history" } }));
    }
  }

  const copyId = (id) => {
    navigator.clipboard?.writeText(id).then(() => toast.success("Batch ID copied"));
  };

  const MOVE_LABEL = {
    receive: "Received to Vault", issue_packing: "Issued to Packing",
    issue_manicuring: "Issued to Manicuring", return_manicuring: "Returned from Manicuring",
  };

  return (
    <div className="flex flex-col h-full overflow-hidden">
      <TopBar
        title="Batch Registry"
        actions={
          <div className="flex items-center gap-2">
            <ProductionGuideButton />
            <BtnSecondary onClick={load} disabled={loading}>
              <RefreshCw size={14} className={loading ? "animate-spin" : ""} />
              Refresh
            </BtnSecondary>
          </div>
        }
      />

      <div className="flex-1 overflow-y-auto p-6">
        <div className="max-w-4xl mx-auto w-full space-y-6">

          {/* Odoo mode banner */}
          {meta && !meta.odoo_writes_live && (
            <div className="flex items-center gap-2 text-xs text-amber-700 dark:text-amber-300 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg px-4 py-2.5">
              <CloudOff size={14} />
              Stock system connection for the production facility is pending. Batches are recorded here and will be created in the stock system automatically once the connection is switched on.
            </div>
          )}

          {/* Generator hero */}
          <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5">
            <div className="flex items-center justify-between mb-1">
              <h3 className="text-sm font-semibold text-gray-800 dark:text-gray-100 flex items-center gap-2">
                <Sparkles size={15} className="text-bassani-500" /> Generate Batch ID
              </h3>
              {can("production.manage") && (
                <button onClick={openManage} className="text-xs text-bassani-600 dark:text-bassani-400 hover:underline flex items-center gap-1">
                  <Plus size={12} /> Manage products
                </button>
              )}
            </div>
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-1">
              Pick the batch type and product. The ID is built automatically to the Bassani V6 standard, with the next sequence number and today's date.
            </p>
            <p className="text-xs text-gray-400 dark:text-gray-500 mb-4">
              This creates batches for stock produced at Bassani only. Imported stock is registered on the{" "}
              <button onClick={() => navigate("/production/receiving")} className="text-bassani-600 dark:text-bassani-400 hover:underline font-medium">S6 Receiving</button>{" "}
              page, where receiving the delivery creates the batch automatically.
            </p>

            <div className="grid sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1.5">Batch type</label>
                <div className="flex flex-wrap gap-1.5">
                  {(meta?.families || []).map(f => (
                    <button
                      key={f.key}
                      onClick={() => setFamily(f.key)}
                      className={`text-xs px-3 py-1.5 rounded-lg font-medium transition-colors ${
                        family === f.key
                          ? "bg-bassani-100 text-bassani-700 dark:bg-bassani-900/40 dark:text-bassani-300 ring-1 ring-bassani-300 dark:ring-bassani-700"
                          : "bg-gray-50 dark:bg-gray-900 text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 border border-gray-200 dark:border-gray-700"
                      }`}
                    >
                      {f.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Product picker */}
              <div ref={productBoxRef} className="relative">
                <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1.5">
                  Product
                </label>
                <input
                  value={product ? `${product.name} (${product.code})` : productQuery}
                  onChange={e => { setProduct(null); setProductQuery(e.target.value); setProductOpen(true); }}
                  onFocus={() => setProductOpen(true)}
                  placeholder="Search by name or shortcode…"
                  className="w-full text-sm border border-gray-200 dark:border-gray-600 rounded-lg px-3 py-2 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-bassani-400"
                />
                {productOpen && (
                  <div className="absolute z-20 mt-1 w-full max-h-56 overflow-y-auto bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-lg">
                    {filteredProducts.length === 0 ? (
                      <p className="text-xs text-gray-400 px-3 py-2">No matching products</p>
                    ) : filteredProducts.map(s => (
                      <button
                        key={s.code}
                        onClick={() => { setProduct(s); setProductQuery(""); setProductOpen(false); }}
                        className="w-full text-left px-3 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-gray-700/50 flex justify-between items-center"
                      >
                        <span className="truncate">{s.name}</span>
                        <span className="font-mono text-xs text-gray-400 ml-2">{s.code}</span>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Live preview */}
            <div className="mt-4 flex flex-col sm:flex-row sm:items-center gap-3">
              <div className="flex-1 bg-gray-50 dark:bg-gray-900 border border-dashed border-gray-300 dark:border-gray-600 rounded-lg px-4 py-3">
                {preview ? (
                  <div className="flex items-center justify-between gap-2">
                    <span className="font-mono text-lg font-semibold text-gray-800 dark:text-gray-100 tracking-wide">{preview.batch_id}</span>
                    <button onClick={() => copyId(preview.batch_id)} className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200" title="Copy">
                      <Copy size={14} />
                    </button>
                  </div>
                ) : (
                  <span className="text-sm text-gray-400">Select a product to preview the next batch ID</span>
                )}
              </div>
              <BtnPrimary onClick={generate} disabled={!preview || generating}>
                {generating ? <Loader2 size={14} className="animate-spin mr-1.5" /> : <Sparkles size={14} className="mr-1.5" />}
                {generating ? "Creating…" : "Create Batch"}
              </BtnPrimary>
            </div>
          </div>

          {/* Registry table */}
          <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden">
            <div className="flex items-center justify-between px-5 py-3 border-b border-gray-100 dark:border-gray-700 gap-3">
              <h3 className="text-sm font-semibold text-gray-800 dark:text-gray-100 flex items-center gap-2">
                <Layers size={15} className="text-gray-400" /> Registry
              </h3>
              <input
                value={q}
                onChange={e => setQ(e.target.value)}
                placeholder="Search batch or product…"
                className="text-xs border border-gray-200 dark:border-gray-600 rounded-lg px-3 py-1.5 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-bassani-400 w-56"
              />
            </div>

            {loading ? (
              <div className="flex items-center justify-center py-12 text-gray-400">
                <Loader2 size={18} className="animate-spin mr-2" /> <span className="text-sm">Loading…</span>
              </div>
            ) : items.length === 0 ? (
              <div className="text-center py-12 text-gray-400 dark:text-gray-500">
                <Layers size={32} className="mx-auto mb-2 opacity-30" />
                <p className="text-sm">No batches yet. Generate the first one above.</p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-left text-xs font-medium text-gray-500 dark:text-gray-400 bg-gray-50 dark:bg-gray-900/50">
                      <th className="px-5 py-2.5">Batch</th>
                      <th className="px-5 py-2.5">Product</th>
                      <th className="px-5 py-2.5">Current stage</th>
                      <th className="px-5 py-2.5">Started</th>
                      <th className="px-5 py-2.5">Stock system</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100 dark:divide-gray-700">
                    {groups.map(g => {
                      const isOpen = !!expandedGroups[g.baseId];
                      const detail = groupDetail[g.baseId];
                      return (
                        <Fragment key={g.baseId}>
                          <tr
                            onClick={() => toggleGroup(g.baseId)}
                            className="hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors cursor-pointer"
                          >
                            <td className="px-5 py-3 font-mono text-gray-800 dark:text-gray-200 whitespace-nowrap">
                              <span className="inline-flex items-center gap-1.5">
                                <ChevronRight size={13} className={`text-gray-400 shrink-0 transition-transform ${isOpen ? "rotate-90" : ""}`} />
                                <span title={batchTitle(g.baseId, g.product_name)}>{g.baseId}</span>
                              </span>
                            </td>
                            <td className="px-5 py-3 text-gray-600 dark:text-gray-300 max-w-[180px] truncate">{g.product_name}</td>
                            <td className="px-5 py-3 text-xs whitespace-nowrap">
                              <div className="flex flex-wrap items-center gap-1">
                                {g.leaves.map(l => (
                                  <span key={l.batch_id} className="text-[11px] font-medium px-1.5 py-0.5 rounded bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300">
                                    {l.stage_suffix ? (STAGE_LABELS[l.stage_suffix] || l.stage_suffix) : "Base"}
                                  </span>
                                ))}
                                {g.stageCount > g.leaves.length && (
                                  <span className="text-[10px] text-gray-400 dark:text-gray-500">({g.stageCount} stages)</span>
                                )}
                              </div>
                            </td>
                            <td className="px-5 py-3 text-xs text-gray-400 whitespace-nowrap">
                              {fmtWhen(g.started_at)}
                              <span className="block text-gray-400 dark:text-gray-500">{g.started_by}</span>
                            </td>
                            <td className="px-5 py-3">
                              <SyncBadge status={g.syncStatus} />
                              {g.mixedSync && <span className="block text-[10px] text-gray-400 mt-0.5">Mixed</span>}
                            </td>
                          </tr>
                          {isOpen && (
                            <tr>
                              <td colSpan={5} className="px-5 py-4 bg-gray-50/70 dark:bg-gray-900/40">
                                {!detail || detail.loading ? (
                                  <div className="flex items-center gap-2 text-gray-400 text-sm py-2">
                                    <Loader2 size={14} className="animate-spin" /> Loading history…
                                  </div>
                                ) : detail.error ? (
                                  <p className="text-sm text-red-500">{detail.error}</p>
                                ) : (
                                  <div className="space-y-4">
                                    {/* Stage chain */}
                                    <div>
                                      <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1.5">Stages of this batch</p>
                                      <div className="flex flex-wrap gap-1.5">
                                        {detail.stages.map(s => (
                                          <span key={s.batch_id} title={batchTitle(s.batch_id, s.product_name)} className="inline-flex items-center gap-1.5 font-mono text-xs px-2 py-1 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-300">
                                            {s.batch_id}
                                            {stageLabel(s.batch_id) && <span className="font-sans text-gray-400"> · {stageLabel(s.batch_id)}</span>}
                                            <SyncDot status={s.odoo_sync} />
                                          </span>
                                        ))}
                                      </div>
                                      {detail.stages.filter(s => s.odoo_error).map(s => (
                                        <p key={s.batch_id} className="text-xs text-red-500 flex items-center gap-1 mt-1.5">
                                          <AlertCircle size={11} /> {s.batch_id}: {s.odoo_error}
                                        </p>
                                      ))}
                                    </div>

                                    {/* Movement history */}
                                    <div>
                                      <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1.5">Vault movements</p>
                                      {detail.movements.length === 0 ? (
                                        <p className="text-sm text-gray-400">No vault movements recorded for this batch yet.</p>
                                      ) : (
                                        <div className="space-y-1.5">
                                          {detail.movements.map(m => (
                                            <div key={m.id} className="flex items-start justify-between gap-3 text-sm bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 rounded-lg px-3 py-2">
                                              <div className="min-w-0">
                                                <p className="text-gray-700 dark:text-gray-200 text-xs font-medium">{MOVE_LABEL[m.type] || m.type}</p>
                                                <p className="text-xs text-gray-400">
                                                  {fmtWhen(m.created_at)} · {m.actor_name}
                                                </p>
                                                {(m.outputs || []).length > 0 && (
                                                  <p className="text-xs text-gray-500 dark:text-gray-400 font-mono mt-0.5">
                                                    {m.outputs.map(o => `${o.batch_id} +${o.qty_g}g`).join("  ")}
                                                  </p>
                                                )}
                                              </div>
                                              <div className="text-right shrink-0">
                                                {m.qty_g != null && (
                                                  <p className="text-xs font-semibold text-gray-700 dark:text-gray-200">
                                                    {m.type === "receive" ? "+" : "-"}{m.qty_g} g
                                                  </p>
                                                )}
                                                <SyncBadge status={m.odoo_sync} />
                                              </div>
                                            </div>
                                          ))}
                                        </div>
                                      )}
                                    </div>
                                  </div>
                                )}
                              </td>
                            </tr>
                          )}
                        </Fragment>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Manage products modal */}
      {manageOpen && (
        <Modal title="Manage Products" onClose={() => setManageOpen(false)} width="max-w-2xl">
          <p className="text-sm text-gray-600 dark:text-gray-300 mb-4">
            The master shortcode list used for batch ID generation. Linking a product to its record in the stock system makes every batch, movement and receipt for it target the exact record, instead of matching by name. Archiving hides a product from the picker without touching its existing batches. Deleting is only possible for products that have never been used on a batch.
          </p>

          {/* Add row */}
          <div className="flex flex-col sm:flex-row gap-2 mb-4">
            <input
              value={newProduct.name}
              onChange={e => setNewProduct(v => ({ ...v, name: e.target.value }))}
              placeholder="Product or flavour name"
              className="flex-1 text-sm border border-gray-200 dark:border-gray-600 rounded-lg px-3 py-2 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-bassani-400"
            />
            <input
              value={newProduct.code}
              onChange={e => setNewProduct(v => ({ ...v, code: e.target.value.toUpperCase() }))}
              maxLength={4}
              placeholder="Code"
              className="w-full sm:w-24 text-sm font-mono border border-gray-200 dark:border-gray-600 rounded-lg px-3 py-2 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-bassani-400"
            />
            <BtnPrimary onClick={saveProduct} disabled={savingProduct || !newProduct.name.trim() || newProduct.code.trim().length < 2}>
              {savingProduct ? "Adding…" : "Add"}
            </BtnPrimary>
          </div>

          {/* Search */}
          <input
            value={manageSearch}
            onChange={e => setManageSearch(e.target.value)}
            placeholder="Search list…"
            className="w-full text-xs border border-gray-200 dark:border-gray-600 rounded-lg px-3 py-1.5 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-bassani-400 mb-2"
          />

          {/* List */}
          <div className="max-h-72 overflow-y-auto divide-y divide-gray-100 dark:divide-gray-700 border border-gray-100 dark:border-gray-700 rounded-lg">
            {manageList
              .filter(s => {
                const t = manageSearch.trim().toLowerCase();
                return !t || s.name.toLowerCase().includes(t) || s.code.toLowerCase().includes(t);
              })
              .map(s => (
                <div key={s.code} className={`flex items-center gap-3 px-3 py-2 text-sm ${s.active ? "" : "opacity-60"}`}>
                  <span className="font-mono text-xs font-semibold text-gray-500 dark:text-gray-400 w-12 shrink-0">{s.code}</span>
                  <div className="flex-1 min-w-0">
                    <span className="block truncate text-gray-700 dark:text-gray-200">{s.name}</span>
                    {s.odoo_product_name ? (
                      <span className="block text-xs text-green-600 dark:text-green-400 truncate flex items-center gap-1">
                        <Link2 size={10} /> Linked to {s.odoo_product_name}
                      </span>
                    ) : (
                      <span className="block text-xs text-amber-600 dark:text-amber-400">Not linked to a stock system product</span>
                    )}
                  </div>
                  {!s.active && (
                    <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-gray-100 text-gray-500 dark:bg-gray-700 dark:text-gray-300 shrink-0">Archived</span>
                  )}
                  {s.odoo_product_name ? (
                    <button onClick={() => doUnlinkProduct(s)} disabled={productBusy === s.code}
                      className="text-xs text-gray-400 hover:text-red-500 shrink-0 transition-colors">
                      Unlink
                    </button>
                  ) : (
                    <button onClick={() => openLinkPicker(s)} disabled={productBusy === s.code}
                      className="text-xs text-bassani-600 dark:text-bassani-400 hover:underline shrink-0">
                      Link product
                    </button>
                  )}
                  <button
                    onClick={() => toggleProduct(s)}
                    disabled={productBusy === s.code}
                    className="text-xs text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 shrink-0"
                  >
                    {s.active ? "Archive" : "Restore"}
                  </button>
                  <button
                    onClick={() => setDeleteProductConfirm(s)}
                    disabled={productBusy === s.code}
                    className="text-xs text-gray-400 hover:text-red-500 transition-colors shrink-0"
                  >
                    Delete
                  </button>
                </div>
              ))}
            {manageList.length === 0 && (
              <p className="text-xs text-gray-400 px-3 py-4 text-center">Loading product list…</p>
            )}
          </div>

          <div className="flex justify-end mt-4">
            <BtnSecondary onClick={() => setManageOpen(false)}>Close</BtnSecondary>
          </div>
        </Modal>
      )}

      {/* Delete product confirm */}
      {deleteProductConfirm && (
        <Modal title="Delete Product" onClose={() => setDeleteProductConfirm(null)}>
          <p className="text-sm text-gray-600 dark:text-gray-300 mb-4">
            Permanently remove <strong>{deleteProductConfirm.name}</strong>{" "}
            (<span className="font-mono">{deleteProductConfirm.code}</span>) from the master list?
            This only works if no batch has ever used this code. If it has been used, archive it instead.
          </p>
          <div className="flex justify-end gap-2">
            <BtnSecondary onClick={() => setDeleteProductConfirm(null)}>Cancel</BtnSecondary>
            <BtnDanger onClick={doDeleteProduct}>Delete</BtnDanger>
          </div>
        </Modal>
      )}

      {/* Link-to-Odoo-product picker — same category/variant/search browsing
          as the quote builder's Browse Products drawer */}
      {linkTarget && (
        <Modal title={`Link ${linkTarget.name}`} onClose={() => setLinkTarget(null)} width="max-w-2xl">
          <p className="text-sm text-gray-600 dark:text-gray-300 mb-3">
            Search or filter by category and variant to find the stock system record that belongs to <strong>{linkTarget.name}</strong>. Every batch, movement and receipt for this product will then always target that exact record. Products are created in the stock system, not here — if it doesn't exist yet, create it there first.
          </p>

          {/* Search bar */}
          <div className="relative mb-2.5">
            <Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
            <input
              value={odooProductQuery}
              onChange={e => setOdooProductQuery(e.target.value)}
              placeholder="Search by product name or SKU…"
              autoFocus
              className="w-full text-sm pl-9 pr-3 py-2.5 border border-gray-200 dark:border-gray-600 rounded-xl bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-bassani-400"
            />
          </div>

          {/* Category + variant filter bar */}
          <div className="flex items-center gap-2 mb-3">
            <SearchableSelect
              value={linkSelectedCat}
              onChange={(v) => { setLinkSelectedCat(v); setLinkSelectedVariant(null); }}
              options={linkCategoryOptions}
              placeholder="All categories"
              searchPlaceholder="Search categories…"
            />
            <SearchableSelect
              value={linkSelectedVariant}
              onChange={setLinkSelectedVariant}
              options={linkVariantOptions}
              placeholder="All variants"
              searchPlaceholder="Search variants…"
              disabled={linkVariantOptions.length === 0}
            />
          </div>

          {/* Results */}
          <div className="max-h-72 overflow-y-auto divide-y divide-gray-100 dark:divide-gray-700 border border-gray-100 dark:border-gray-700 rounded-lg">
            {odooProductSearching ? (
              <p className="text-xs text-gray-400 px-3 py-6 flex items-center justify-center gap-2"><Loader2 size={13} className="animate-spin" /> Searching…</p>
            ) : !odooProductQuery.trim() && !linkSelectedCat ? (
              <div className="flex flex-col items-center justify-center text-center px-8 py-8">
                <Package size={22} className="text-gray-300 dark:text-gray-600 mb-2" />
                <p className="text-xs text-gray-400">Select a category or search to browse the stock system's products.</p>
              </div>
            ) : linkDisplayedProducts.length === 0 ? (
              <p className="text-xs text-gray-400 px-3 py-6 text-center">
                No products found. Check the name, or create the product in the stock system first.
              </p>
            ) : linkDisplayedProducts.map(p => {
              const { base, groups } = parseDisplayName(p.display_name || p.name || "");
              return (
                <button
                  key={p.id}
                  onClick={() => doLinkProduct(p)}
                  className="w-full text-left px-3 py-2.5 text-sm hover:bg-gray-50 dark:hover:bg-gray-700/50 flex items-center justify-between gap-3"
                >
                  <div className="min-w-0">
                    <span className="block text-gray-800 dark:text-gray-100 font-medium truncate">{base}</span>
                    <div className="flex items-center gap-1.5 mt-1 flex-wrap">
                      {groups.map((g, i) => (
                        <span key={i} className="text-[10px] bg-bassani-50 dark:bg-bassani-900/30 text-bassani-700 dark:text-bassani-300 rounded px-1.5 py-0.5 font-medium leading-none">
                          {g}
                        </span>
                      ))}
                      {p.default_code && (
                        <span className="text-[10px] font-mono text-gray-400">{p.default_code}</span>
                      )}
                    </div>
                  </div>
                  <span className="text-xs font-semibold text-bassani-600 dark:text-bassani-400 shrink-0">Link</span>
                </button>
              );
            })}
          </div>
          {!odooProductSearching && linkDisplayedProducts.length > 0 && (
            <p className="text-[11px] text-gray-400 text-center mt-2">
              {linkDisplayedProducts.length} product{linkDisplayedProducts.length !== 1 ? "s" : ""}
              {linkSelectedVariant ? ` · ${linkSelectedVariant}` : ""}
            </p>
          )}

          <div className="flex justify-end mt-4">
            <BtnSecondary onClick={() => setLinkTarget(null)}>Cancel</BtnSecondary>
          </div>
        </Modal>
      )}

    </div>
  );
}
