import { useState, useEffect, useCallback, useRef } from "react";
import { Loader2, RefreshCw, Copy, Sparkles, Plus, Layers, CloudOff, CloudUpload, AlertCircle, CheckCircle } from "lucide-react";
import api from "../api";
import toast from "react-hot-toast";
import { useAuth } from "../AuthContext";
import { TopBar, BtnPrimary, BtnSecondary, Modal } from "../components/UI";
import ProductionGuideButton from "../components/ProductionGuide";

/* Phase 13.0.2 — Batch ID generator + registry.
   Batch IDs are generated by the portal (V6 standard), never typed. */

export const SYNC_BADGE = {
  staged: { label: "Staged",  cls: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300" },
  done:   { label: "In Odoo", cls: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300" },
  error:  { label: "Sync error", cls: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300" },
};

export function SyncBadge({ status }) {
  const b = SYNC_BADGE[status] || SYNC_BADGE.staged;
  return <span className={`inline-flex text-xs font-medium px-2 py-0.5 rounded-full ${b.cls}`}>{b.label}</span>;
}

export const fmtWhen = (v) =>
  v ? new Date(v).toLocaleString("en-ZA", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Africa/Johannesburg" }) : "";

export default function BatchRegistry() {
  const { can } = useAuth();
  const [meta, setMeta]         = useState(null);
  const [strains, setStrains]   = useState([]);
  const [items, setItems]       = useState([]);
  const [loading, setLoading]   = useState(true);
  const [q, setQ]               = useState("");

  // Generator state
  const [family, setFamily]         = useState("single");
  const [strainQuery, setStrainQuery] = useState("");
  const [strain, setStrain]         = useState(null);   // {name, code}
  const [strainOpen, setStrainOpen] = useState(false);
  const [preview, setPreview]       = useState(null);   // {batch_id, sequence}
  const [generating, setGenerating] = useState(false);
  const strainBoxRef = useRef(null);

  // Add-strain modal (production.manage)
  const [addStrainOpen, setAddStrainOpen] = useState(false);
  const [newStrain, setNewStrain]         = useState({ name: "", code: "" });
  const [savingStrain, setSavingStrain]   = useState(false);

  // Timeline modal
  const [timeline, setTimeline]           = useState(null);
  const [timelineLoading, setTimelineLoading] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [metaRes, strainRes, listRes] = await Promise.all([
        api.get("/api/production/meta"),
        api.get("/api/production/strains"),
        api.get("/api/production/batches", { params: q ? { q, limit: 200 } : { limit: 200 } }),
      ]);
      setMeta(metaRes.data);
      setStrains(strainRes.data.strains);
      setItems(listRes.data.items);
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to load batch registry");
    } finally {
      setLoading(false);
    }
  }, [q]);

  useEffect(() => { load(); }, [load]);

  // Live ID preview as the operator picks family + strain
  useEffect(() => {
    if (!strain) { setPreview(null); return; }
    let stale = false;
    api.get("/api/production/batches/preview", { params: { family, strain_code: strain.code } })
      .then(r => { if (!stale) setPreview(r.data); })
      .catch(() => { if (!stale) setPreview(null); });
    return () => { stale = true; };
  }, [family, strain]);

  // Close strain dropdown on outside click
  useEffect(() => {
    const close = (e) => {
      if (strainBoxRef.current && !strainBoxRef.current.contains(e.target)) setStrainOpen(false);
    };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, []);

  const filteredStrains = strains.filter(s => {
    const t = strainQuery.trim().toLowerCase();
    if (!t) return true;
    return s.name.toLowerCase().includes(t) || s.code.toLowerCase().includes(t);
  });

  async function generate() {
    if (!strain || !preview) return;
    setGenerating(true);
    try {
      const r = await api.post("/api/production/batches", { family, strain_code: strain.code });
      toast.success(`Batch ${r.data.batch.batch_id} created`);
      setItems(prev => [r.data.batch, ...prev]);
      setPreview(null);
      // refresh the preview for the next sequence number
      const p = await api.get("/api/production/batches/preview", { params: { family, strain_code: strain.code } });
      setPreview(p.data);
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to create batch");
    } finally {
      setGenerating(false);
    }
  }

  async function saveStrain() {
    setSavingStrain(true);
    try {
      await api.post("/api/production/strains", { name: newStrain.name, code: newStrain.code });
      toast.success(`Strain ${newStrain.name} added`);
      setAddStrainOpen(false);
      setNewStrain({ name: "", code: "" });
      const r = await api.get("/api/production/strains");
      setStrains(r.data.strains);
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to add strain");
    } finally {
      setSavingStrain(false);
    }
  }

  async function openTimeline(batchId) {
    setTimelineLoading(true);
    setTimeline({ batch_id: batchId });
    try {
      const r = await api.get(`/api/production/batches/${encodeURIComponent(batchId)}/timeline`);
      setTimeline(r.data);
    } catch (e) {
      toast.error(e.response?.data?.detail || "Failed to load batch timeline");
      setTimeline(null);
    } finally {
      setTimelineLoading(false);
    }
  }

  const copyId = (id) => {
    navigator.clipboard?.writeText(id).then(() => toast.success("Batch ID copied"));
  };

  const MOVE_LABEL = {
    receive: "Received to Vault", issue_packing: "Issued to Packing",
    issue_manicuring: "Issued to Manicuring", return_manicuring: "Returned from Manicuring",
  };

  return (
    <div className="flex flex-col h-full overflow-hidden">
      <TopBar
        title="Batch Registry"
        actions={
          <div className="flex items-center gap-2">
            <ProductionGuideButton />
            <BtnSecondary onClick={load} disabled={loading}>
              <RefreshCw size={14} className={loading ? "animate-spin" : ""} />
              Refresh
            </BtnSecondary>
          </div>
        }
      />

      <div className="flex-1 overflow-y-auto p-6">
        <div className="max-w-4xl mx-auto w-full space-y-6">

          {/* Odoo mode banner */}
          {meta && !meta.odoo_writes_live && (
            <div className="flex items-center gap-2 text-xs text-amber-700 dark:text-amber-300 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg px-4 py-2.5">
              <CloudOff size={14} />
              Stock system connection for the production facility is pending. Batches are recorded here and will be created in the stock system automatically once the connection is switched on.
            </div>
          )}

          {/* Generator hero */}
          <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5">
            <div className="flex items-center justify-between mb-1">
              <h3 className="text-sm font-semibold text-gray-800 dark:text-gray-100 flex items-center gap-2">
                <Sparkles size={15} className="text-bassani-500" /> Generate Batch ID
              </h3>
              {can("production.manage") && (
                <button onClick={() => setAddStrainOpen(true)} className="text-xs text-bassani-600 dark:text-bassani-400 hover:underline flex items-center gap-1">
                  <Plus size={12} /> Add strain
                </button>
              )}
            </div>
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-4">
              Pick the batch type and strain. The ID is built automatically to the Bassani V6 standard, with the next sequence number and today's date.
            </p>

            <div className="grid sm:grid-cols-2 gap-4">
              {/* Family */}
              <div>
                <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1.5">Batch type</label>
                <div className="flex flex-wrap gap-1.5">
                  {(meta?.families || []).map(f => (
                    <button
                      key={f.key}
                      onClick={() => setFamily(f.key)}
                      className={`text-xs px-3 py-1.5 rounded-lg font-medium transition-colors ${
                        family === f.key
                          ? "bg-bassani-100 text-bassani-700 dark:bg-bassani-900/40 dark:text-bassani-300 ring-1 ring-bassani-300 dark:ring-bassani-700"
                          : "bg-gray-50 dark:bg-gray-900 text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 border border-gray-200 dark:border-gray-700"
                      }`}
                    >
                      {f.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Strain picker */}
              <div ref={strainBoxRef} className="relative">
                <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1.5">
                  {family === "gummy" ? "Flavour" : "Strain"}
                </label>
                <input
                  value={strain ? `${strain.name} (${strain.code})` : strainQuery}
                  onChange={e => { setStrain(null); setStrainQuery(e.target.value); setStrainOpen(true); }}
                  onFocus={() => setStrainOpen(true)}
                  placeholder="Search by name or shortcode…"
                  className="w-full text-sm border border-gray-200 dark:border-gray-600 rounded-lg px-3 py-2 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-bassani-400"
                />
                {strainOpen && (
                  <div className="absolute z-20 mt-1 w-full max-h-56 overflow-y-auto bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-lg">
                    {filteredStrains.length === 0 ? (
                      <p className="text-xs text-gray-400 px-3 py-2">No matching strains</p>
                    ) : filteredStrains.map(s => (
                      <button
                        key={s.code}
                        onClick={() => { setStrain(s); setStrainQuery(""); setStrainOpen(false); }}
                        className="w-full text-left px-3 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-gray-700/50 flex justify-between items-center"
                      >
                        <span className="truncate">{s.name}</span>
                        <span className="font-mono text-xs text-gray-400 ml-2">{s.code}</span>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Live preview */}
            <div className="mt-4 flex flex-col sm:flex-row sm:items-center gap-3">
              <div className="flex-1 bg-gray-50 dark:bg-gray-900 border border-dashed border-gray-300 dark:border-gray-600 rounded-lg px-4 py-3">
                {preview ? (
                  <div className="flex items-center justify-between gap-2">
                    <span className="font-mono text-lg font-semibold text-gray-800 dark:text-gray-100 tracking-wide">{preview.batch_id}</span>
                    <button onClick={() => copyId(preview.batch_id)} className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200" title="Copy">
                      <Copy size={14} />
                    </button>
                  </div>
                ) : (
                  <span className="text-sm text-gray-400">Select a strain to preview the next batch ID</span>
                )}
              </div>
              <BtnPrimary onClick={generate} disabled={!preview || generating}>
                {generating ? <Loader2 size={14} className="animate-spin mr-1.5" /> : <Sparkles size={14} className="mr-1.5" />}
                {generating ? "Creating…" : "Create Batch"}
              </BtnPrimary>
            </div>
          </div>

          {/* Registry table */}
          <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden">
            <div className="flex items-center justify-between px-5 py-3 border-b border-gray-100 dark:border-gray-700 gap-3">
              <h3 className="text-sm font-semibold text-gray-800 dark:text-gray-100 flex items-center gap-2">
                <Layers size={15} className="text-gray-400" /> Registry
              </h3>
              <input
                value={q}
                onChange={e => setQ(e.target.value)}
                placeholder="Search batch or strain…"
                className="text-xs border border-gray-200 dark:border-gray-600 rounded-lg px-3 py-1.5 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-bassani-400 w-56"
              />
            </div>

            {loading ? (
              <div className="flex items-center justify-center py-12 text-gray-400">
                <Loader2 size={18} className="animate-spin mr-2" /> <span className="text-sm">Loading…</span>
              </div>
            ) : items.length === 0 ? (
              <div className="text-center py-12 text-gray-400 dark:text-gray-500">
                <Layers size={32} className="mx-auto mb-2 opacity-30" />
                <p className="text-sm">No batches yet. Generate the first one above.</p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-left text-xs font-medium text-gray-500 dark:text-gray-400 bg-gray-50 dark:bg-gray-900/50">
                      <th className="px-5 py-2.5">Batch ID</th>
                      <th className="px-5 py-2.5">Strain</th>
                      <th className="px-5 py-2.5">Stage</th>
                      <th className="px-5 py-2.5">Created</th>
                      <th className="px-5 py-2.5">By</th>
                      <th className="px-5 py-2.5">Stock system</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100 dark:divide-gray-700">
                    {items.map(b => (
                      <tr
                        key={b.batch_id}
                        onClick={() => openTimeline(b.batch_id)}
                        className="hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors cursor-pointer"
                      >
                        <td className="px-5 py-3 font-mono text-gray-800 dark:text-gray-200 whitespace-nowrap">{b.batch_id}</td>
                        <td className="px-5 py-3 text-gray-600 dark:text-gray-300 max-w-[180px] truncate">{b.strain_name}</td>
                        <td className="px-5 py-3 text-xs text-gray-500 dark:text-gray-400">
                          {b.stage_suffix
                            ? <span className="font-mono">-{b.stage_suffix}</span>
                            : <span className="text-gray-300 dark:text-gray-600">Base</span>}
                        </td>
                        <td className="px-5 py-3 text-xs text-gray-400 whitespace-nowrap">{fmtWhen(b.created_at)}</td>
                        <td className="px-5 py-3 text-xs text-gray-500 dark:text-gray-400 whitespace-nowrap">{b.created_by_name}</td>
                        <td className="px-5 py-3"><SyncBadge status={b.odoo_sync} /></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Add strain modal */}
      {addStrainOpen && (
        <Modal title="Add Strain Shortcode" onClose={() => setAddStrainOpen(false)}>
          <p className="text-sm text-gray-600 dark:text-gray-300 mb-4">
            Adds a strain to the master shortcode list used for batch ID generation.
          </p>
          <div className="space-y-3">
            <div>
              <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">Strain name</label>
              <input
                value={newStrain.name}
                onChange={e => setNewStrain(v => ({ ...v, name: e.target.value }))}
                className="w-full text-sm border border-gray-200 dark:border-gray-600 rounded-lg px-3 py-2 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-bassani-400"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">Shortcode (2-4 letters)</label>
              <input
                value={newStrain.code}
                onChange={e => setNewStrain(v => ({ ...v, code: e.target.value.toUpperCase() }))}
                maxLength={4}
                className="w-full text-sm font-mono border border-gray-200 dark:border-gray-600 rounded-lg px-3 py-2 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-bassani-400"
              />
            </div>
          </div>
          <div className="flex justify-end gap-2 mt-4">
            <BtnSecondary onClick={() => setAddStrainOpen(false)}>Cancel</BtnSecondary>
            <BtnPrimary onClick={saveStrain} disabled={savingStrain || !newStrain.name.trim() || newStrain.code.trim().length < 2}>
              {savingStrain ? "Saving…" : "Add Strain"}
            </BtnPrimary>
          </div>
        </Modal>
      )}

      {/* Timeline modal */}
      {timeline && (
        <Modal title={`Batch ${timeline.batch?.batch_id || timeline.batch_id}`} onClose={() => setTimeline(null)}>
          {timelineLoading ? (
            <div className="flex items-center justify-center py-8 text-gray-400">
              <Loader2 size={18} className="animate-spin mr-2" /> <span className="text-sm">Loading…</span>
            </div>
          ) : timeline.batch ? (
            <div className="space-y-4">
              <div className="flex items-center gap-2 flex-wrap text-sm">
                <span className="text-gray-500 dark:text-gray-400">{timeline.batch.strain_name}</span>
                <SyncBadge status={timeline.batch.odoo_sync} />
                {timeline.batch.odoo_error && (
                  <span className="text-xs text-red-500 flex items-center gap-1"><AlertCircle size={12} /> {timeline.batch.odoo_error}</span>
                )}
              </div>

              {/* Stage chain */}
              <div>
                <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1.5">Stages of this batch</p>
                <div className="flex flex-wrap gap-1.5">
                  {timeline.stages.map(s => (
                    <span key={s.batch_id} className={`font-mono text-xs px-2 py-1 rounded-lg border ${
                      s.batch_id === timeline.batch.batch_id
                        ? "border-bassani-300 bg-bassani-50 text-bassani-700 dark:bg-bassani-900/30 dark:border-bassani-700 dark:text-bassani-300"
                        : "border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300"
                    }`}>
                      {s.batch_id}
                    </span>
                  ))}
                </div>
              </div>

              {/* Movement history */}
              <div>
                <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1.5">Vault movements</p>
                {timeline.movements.length === 0 ? (
                  <p className="text-sm text-gray-400">No vault movements recorded for this batch yet.</p>
                ) : (
                  <div className="space-y-1.5 max-h-64 overflow-y-auto pr-1">
                    {timeline.movements.map(m => (
                      <div key={m.id} className="flex items-start justify-between gap-3 text-sm bg-gray-50 dark:bg-gray-900 rounded-lg px-3 py-2">
                        <div className="min-w-0">
                          <p className="text-gray-700 dark:text-gray-200 text-xs font-medium">{MOVE_LABEL[m.type] || m.type}</p>
                          <p className="text-xs text-gray-400">
                            {fmtWhen(m.created_at)} · {m.actor_name}
                          </p>
                          {(m.outputs || []).length > 0 && (
                            <p className="text-xs text-gray-500 dark:text-gray-400 font-mono mt-0.5">
                              {m.outputs.map(o => `${o.batch_id} +${o.qty_g}g`).join("  ")}
                            </p>
                          )}
                        </div>
                        <div className="text-right shrink-0">
                          {m.qty_g != null && (
                            <p className="text-xs font-semibold text-gray-700 dark:text-gray-200">
                              {m.type === "receive" ? "+" : "-"}{m.qty_g} g
                            </p>
                          )}
                          <SyncBadge status={m.odoo_sync} />
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {timeline.batch.odoo_sync === "done" && (
                <p className="text-xs text-green-600 dark:text-green-400 flex items-center gap-1">
                  <CheckCircle size={12} /> This batch exists in the stock system.
                </p>
              )}
              {timeline.batch.odoo_sync === "staged" && (
                <p className="text-xs text-amber-600 dark:text-amber-400 flex items-center gap-1">
                  <CloudUpload size={12} /> Queued for the stock system. It will be created automatically once the production facility connection is live.
                </p>
              )}
            </div>
          ) : null}
        </Modal>
      )}
    </div>
  );
}
